development: &dev
  secret_key_base: 
  telegram:
    bot:
      token: BOT_TOKEN
      username: BOT_NAME
      # async: true
      # botan:
      #   token: botan_token
      #   # async: true

test:
  secret_key_base: 
  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME

production:
  <<: *dev
